/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as IaRouteImport } from './routes/ia'
import { Route as CulturaRouteImport } from './routes/cultura'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicosIndexRouteImport } from './routes/servicos.index'
import { Route as NoticiasIndexRouteImport } from './routes/noticias.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as ServicosSlugRouteImport } from './routes/servicos.$slug'
import { Route as NoticiasSlugRouteImport } from './routes/noticias.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ApiChatRouteImport } from './routes/api/chat'
// Admin routes
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminNewsRouteImport } from './routes/admin/news'
import { Route as AdminNewsIdRouteImport } from './routes/admin/news.$id'
import { Route as AdminBlogRouteImport } from './routes/admin/blog'
import { Route as AdminBlogIdRouteImport } from './routes/admin/blog.$id'
import { Route as AdminCasesRouteImport } from './routes/admin/cases'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as AdminInstagramRouteImport } from './routes/admin/instagram'
import { Route as AdminImportRouteImport } from './routes/admin/import'

// Public routes
const SobreRoute = SobreRouteImport.update({ id: '/sobre', path: '/sobre', getParentRoute: () => rootRouteImport } as any)
const IaRoute = IaRouteImport.update({ id: '/ia', path: '/ia', getParentRoute: () => rootRouteImport } as any)
const CulturaRoute = CulturaRouteImport.update({ id: '/cultura', path: '/cultura', getParentRoute: () => rootRouteImport } as any)
const ContatoRoute = ContatoRouteImport.update({ id: '/contato', path: '/contato', getParentRoute: () => rootRouteImport } as any)
const CasesRoute = CasesRouteImport.update({ id: '/cases', path: '/cases', getParentRoute: () => rootRouteImport } as any)
const IndexRoute = IndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => rootRouteImport } as any)
const ServicosIndexRoute = ServicosIndexRouteImport.update({ id: '/servicos/', path: '/servicos/', getParentRoute: () => rootRouteImport } as any)
const NoticiasIndexRoute = NoticiasIndexRouteImport.update({ id: '/noticias/', path: '/noticias/', getParentRoute: () => rootRouteImport } as any)
const BlogIndexRoute = BlogIndexRouteImport.update({ id: '/blog/', path: '/blog/', getParentRoute: () => rootRouteImport } as any)
const ServicosSlugRoute = ServicosSlugRouteImport.update({ id: '/servicos/$slug', path: '/servicos/$slug', getParentRoute: () => rootRouteImport } as any)
const NoticiasSlugRoute = NoticiasSlugRouteImport.update({ id: '/noticias/$slug', path: '/noticias/$slug', getParentRoute: () => rootRouteImport } as any)
const BlogSlugRoute = BlogSlugRouteImport.update({ id: '/blog/$slug', path: '/blog/$slug', getParentRoute: () => rootRouteImport } as any)
const ApiChatRoute = ApiChatRouteImport.update({ id: '/api/chat', path: '/api/chat', getParentRoute: () => rootRouteImport } as any)

// Admin routes
const AdminRoute = AdminRouteImport.update({ id: '/admin', path: '/admin', getParentRoute: () => rootRouteImport } as any)
const AdminLoginRoute = AdminLoginRouteImport.update({ id: '/admin/login', path: '/admin/login', getParentRoute: () => rootRouteImport } as any)
const AdminIndexRoute = AdminIndexRouteImport.update({ id: '/admin/', path: '/', getParentRoute: () => AdminRoute } as any)
const AdminNewsRoute = AdminNewsRouteImport.update({ id: '/admin/news', path: '/news', getParentRoute: () => AdminRoute } as any)
const AdminNewsIdRoute = AdminNewsIdRouteImport.update({ id: '/admin/news/$id', path: '/news/$id', getParentRoute: () => AdminRoute } as any)
const AdminBlogRoute = AdminBlogRouteImport.update({ id: '/admin/blog', path: '/blog', getParentRoute: () => AdminRoute } as any)
const AdminBlogIdRoute = AdminBlogIdRouteImport.update({ id: '/admin/blog/$id', path: '/blog/$id', getParentRoute: () => AdminRoute } as any)
const AdminCasesRoute = AdminCasesRouteImport.update({ id: '/admin/cases', path: '/cases', getParentRoute: () => AdminRoute } as any)
const AdminUsersRoute = AdminUsersRouteImport.update({ id: '/admin/users', path: '/users', getParentRoute: () => AdminRoute } as any)
const AdminAuditRoute = AdminAuditRouteImport.update({ id: '/admin/audit', path: '/audit', getParentRoute: () => AdminRoute } as any)
const AdminInstagramRoute = AdminInstagramRouteImport.update({ id: '/admin/instagram', path: '/instagram', getParentRoute: () => AdminRoute } as any)
const AdminImportRoute = AdminImportRouteImport.update({ id: '/admin/import', path: '/import', getParentRoute: () => AdminRoute } as any)

// Admin children
const adminRouteChildren = {
  AdminIndexRoute,
  AdminNewsRoute,
  AdminNewsIdRoute,
  AdminBlogRoute,
  AdminBlogIdRoute,
  AdminCasesRoute,
  AdminUsersRoute,
  AdminAuditRoute,
  AdminInstagramRoute,
  AdminImportRoute,
}
const AdminRouteWithChildren = AdminRoute._addFileChildren(adminRouteChildren)

// Root children
interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CasesRoute: typeof CasesRoute
  ContatoRoute: typeof ContatoRoute
  CulturaRoute: typeof CulturaRoute
  IaRoute: typeof IaRoute
  SobreRoute: typeof SobreRoute
  ApiChatRoute: typeof ApiChatRoute
  BlogSlugRoute: typeof BlogSlugRoute
  NoticiasSlugRoute: typeof NoticiasSlugRoute
  ServicosSlugRoute: typeof ServicosSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  NoticiasIndexRoute: typeof NoticiasIndexRoute
  ServicosIndexRoute: typeof ServicosIndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute,
  CasesRoute,
  ContatoRoute,
  CulturaRoute,
  IaRoute,
  SobreRoute,
  ApiChatRoute,
  BlogSlugRoute,
  NoticiasSlugRoute,
  ServicosSlugRoute,
  BlogIndexRoute,
  NoticiasIndexRoute,
  ServicosIndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AdminLoginRoute,
}

export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cases'
    | '/contato'
    | '/cultura'
    | '/ia'
    | '/sobre'
    | '/api/chat'
    | '/blog/$slug'
    | '/noticias/$slug'
    | '/servicos/$slug'
    | '/blog'
    | '/noticias'
    | '/servicos'
    | '/admin'
    | '/admin/login'
    | '/admin/'
    | '/admin/news'
    | '/admin/news/$id'
    | '/admin/blog'
    | '/admin/blog/$id'
    | '/admin/cases'
    | '/admin/users'
    | '/admin/audit'
    | '/admin/instagram'
    | '/admin/import'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cases'
    | '/contato'
    | '/cultura'
    | '/ia'
    | '/sobre'
    | '/api/chat'
    | '/blog/$slug'
    | '/noticias/$slug'
    | '/servicos/$slug'
    | '/blog'
    | '/noticias'
    | '/servicos'
    | '/admin'
    | '/admin/login'
    | '/admin/'
    | '/admin/news'
    | '/admin/news/$id'
    | '/admin/blog'
    | '/admin/blog/$id'
    | '/admin/cases'
    | '/admin/users'
    | '/admin/audit'
    | '/admin/instagram'
    | '/admin/import'
  id:
    | '__root__'
    | '/'
    | '/cases'
    | '/contato'
    | '/cultura'
    | '/ia'
    | '/sobre'
    | '/api/chat'
    | '/blog/$slug'
    | '/noticias/$slug'
    | '/servicos/$slug'
    | '/blog/'
    | '/noticias/'
    | '/servicos/'
    | '/admin'
    | '/admin/login'
    | '/admin/'
    | '/admin/news'
    | '/admin/news/$id'
    | '/admin/blog'
    | '/admin/blog/$id'
    | '/admin/cases'
    | '/admin/users'
    | '/admin/audit'
    | '/admin/instagram'
    | '/admin/import'
  fileRoutesById: FileRoutesById
}

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cases': typeof CasesRoute
  '/contato': typeof ContatoRoute
  '/cultura': typeof CulturaRoute
  '/ia': typeof IaRoute
  '/sobre': typeof SobreRoute
  '/api/chat': typeof ApiChatRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/servicos/$slug': typeof ServicosSlugRoute
  '/blog': typeof BlogIndexRoute
  '/noticias': typeof NoticiasIndexRoute
  '/servicos': typeof ServicosIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/news/$id': typeof AdminNewsIdRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/cases': typeof AdminCasesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/instagram': typeof AdminInstagramRoute
  '/admin/import': typeof AdminImportRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cases': typeof CasesRoute
  '/contato': typeof ContatoRoute
  '/cultura': typeof CulturaRoute
  '/ia': typeof IaRoute
  '/sobre': typeof SobreRoute
  '/api/chat': typeof ApiChatRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/servicos/$slug': typeof ServicosSlugRoute
  '/blog': typeof BlogIndexRoute
  '/noticias': typeof NoticiasIndexRoute
  '/servicos': typeof ServicosIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/news/$id': typeof AdminNewsIdRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/cases': typeof AdminCasesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/instagram': typeof AdminInstagramRoute
  '/admin/import': typeof AdminImportRoute
}

export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cases': typeof CasesRoute
  '/contato': typeof ContatoRoute
  '/cultura': typeof CulturaRoute
  '/ia': typeof IaRoute
  '/sobre': typeof SobreRoute
  '/api/chat': typeof ApiChatRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/servicos/$slug': typeof ServicosSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/noticias/': typeof NoticiasIndexRoute
  '/servicos/': typeof ServicosIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/news/$id': typeof AdminNewsIdRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/cases': typeof AdminCasesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/instagram': typeof AdminInstagramRoute
  '/admin/import': typeof AdminImportRoute
}
