/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as IaRouteImport } from './routes/ia'
import { Route as CulturaRouteImport } from './routes/cultura'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicosIndexRouteImport } from './routes/servicos.index'
import { Route as NoticiasIndexRouteImport } from './routes/noticias.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ServicosSlugRouteImport } from './routes/servicos.$slug'
import { Route as NoticiasSlugRouteImport } from './routes/noticias.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminResetPasswordRouteImport } from './routes/admin.reset-password'
import { Route as AdminNewsRouteImport } from './routes/admin.news_'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminInstagramRouteImport } from './routes/admin.instagram'
import { Route as AdminImportRouteImport } from './routes/admin.import'
import { Route as AdminForgotPasswordRouteImport } from './routes/admin.forgot-password'
import { Route as AdminFaqRouteImport } from './routes/admin.faq'
import { Route as AdminCasesRouteImport } from './routes/admin.cases_'
import { Route as AdminBlogRouteImport } from './routes/admin.blog_'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminNewsIdRouteImport } from './routes/admin.news.$id'
import { Route as AdminCasesIdRouteImport } from './routes/admin.cases.$id'
import { Route as AdminBlogIdRouteImport } from './routes/admin.blog.$id'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const IaRoute = IaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => rootRouteImport,
} as any)
const CulturaRoute = CulturaRouteImport.update({
  id: '/cultura',
  path: '/cultura',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosIndexRoute = ServicosIndexRouteImport.update({
  id: '/servicos/',
  path: '/servicos/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasIndexRoute = NoticiasIndexRouteImport.update({
  id: '/noticias/',
  path: '/noticias/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ServicosSlugRoute = ServicosSlugRouteImport.update({
  id: '/servicos/$slug',
  path: '/servicos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasSlugRoute = NoticiasSlugRouteImport.update({
  id: '/noticias/$slug',
  path: '/noticias/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResetPasswordRoute = AdminResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewsRoute = AdminNewsRouteImport.update({
  id: '/news_',
  path: '/news',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInstagramRoute = AdminInstagramRouteImport.update({
  id: '/instagram',
  path: '/instagram',
  getParentRoute: () => AdminRoute,
} as any)
const AdminImportRoute = AdminImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AdminRoute,
} as any)
const AdminForgotPasswordRoute = AdminForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFaqRoute = AdminFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCasesRoute = AdminCasesRouteImport.update({
  id: '/cases_',
  path: '/cases',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog_',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewsIdRoute = AdminNewsIdRouteImport.update({
  id: '/news/$id',
  path: '/news/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCasesIdRoute = AdminCasesIdRouteImport.update({
  id: '/cases/$id',
  path: '/cases/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogIdRoute = AdminBlogIdRouteImport.update({
  id: '/blog/$id',
  path: '/blog/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cases': typeof CasesRoute
  '/contato': typeof ContatoRoute
  '/cultura': typeof CulturaRoute
  '/ia': typeof IaRoute
  '/sobre': typeof SobreRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/cases': typeof AdminCasesRoute
  '/admin/faq': typeof AdminFaqRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/instagram': typeof AdminInstagramRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/chat': typeof ApiChatRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/servicos/$slug': typeof ServicosSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/noticias/': typeof NoticiasIndexRoute
  '/servicos/': typeof ServicosIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/cases/$id': typeof AdminCasesIdRoute
  '/admin/news/$id': typeof AdminNewsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cases': typeof CasesRoute
  '/contato': typeof ContatoRoute
  '/cultura': typeof CulturaRoute
  '/ia': typeof IaRoute
  '/sobre': typeof SobreRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/cases': typeof AdminCasesRoute
  '/admin/faq': typeof AdminFaqRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/instagram': typeof AdminInstagramRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/chat': typeof ApiChatRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/servicos/$slug': typeof ServicosSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/noticias': typeof NoticiasIndexRoute
  '/servicos': typeof ServicosIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/cases/$id': typeof AdminCasesIdRoute
  '/admin/news/$id': typeof AdminNewsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cases': typeof CasesRoute
  '/contato': typeof ContatoRoute
  '/cultura': typeof CulturaRoute
  '/ia': typeof IaRoute
  '/sobre': typeof SobreRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/blog_': typeof AdminBlogRoute
  '/admin/cases_': typeof AdminCasesRoute
  '/admin/faq': typeof AdminFaqRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/instagram': typeof AdminInstagramRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/news_': typeof AdminNewsRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/chat': typeof ApiChatRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/servicos/$slug': typeof ServicosSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/noticias/': typeof NoticiasIndexRoute
  '/servicos/': typeof ServicosIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/cases/$id': typeof AdminCasesIdRoute
  '/admin/news/$id': typeof AdminNewsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cases'
    | '/contato'
    | '/cultura'
    | '/ia'
    | '/sobre'
    | '/admin/audit'
    | '/admin/blog'
    | '/admin/cases'
    | '/admin/faq'
    | '/admin/forgot-password'
    | '/admin/import'
    | '/admin/instagram'
    | '/admin/login'
    | '/admin/media'
    | '/admin/news'
    | '/admin/reset-password'
    | '/admin/settings'
    | '/admin/users'
    | '/api/chat'
    | '/blog/$slug'
    | '/noticias/$slug'
    | '/servicos/$slug'
    | '/admin/'
    | '/blog/'
    | '/noticias/'
    | '/servicos/'
    | '/admin/blog/$id'
    | '/admin/cases/$id'
    | '/admin/news/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cases'
    | '/contato'
    | '/cultura'
    | '/ia'
    | '/sobre'
    | '/admin/audit'
    | '/admin/blog'
    | '/admin/cases'
    | '/admin/faq'
    | '/admin/forgot-password'
    | '/admin/import'
    | '/admin/instagram'
    | '/admin/login'
    | '/admin/media'
    | '/admin/news'
    | '/admin/reset-password'
    | '/admin/settings'
    | '/admin/users'
    | '/api/chat'
    | '/blog/$slug'
    | '/noticias/$slug'
    | '/servicos/$slug'
    | '/admin'
    | '/blog'
    | '/noticias'
    | '/servicos'
    | '/admin/blog/$id'
    | '/admin/cases/$id'
    | '/admin/news/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cases'
    | '/contato'
    | '/cultura'
    | '/ia'
    | '/sobre'
    | '/admin/audit'
    | '/admin/blog_'
    | '/admin/cases_'
    | '/admin/faq'
    | '/admin/forgot-password'
    | '/admin/import'
    | '/admin/instagram'
    | '/admin/login'
    | '/admin/media'
    | '/admin/news_'
    | '/admin/reset-password'
    | '/admin/settings'
    | '/admin/users'
    | '/api/chat'
    | '/blog/$slug'
    | '/noticias/$slug'
    | '/servicos/$slug'
    | '/admin/'
    | '/blog/'
    | '/noticias/'
    | '/servicos/'
    | '/admin/blog/$id'
    | '/admin/cases/$id'
    | '/admin/news/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CasesRoute: typeof CasesRoute
  ContatoRoute: typeof ContatoRoute
  CulturaRoute: typeof CulturaRoute
  IaRoute: typeof IaRoute
  SobreRoute: typeof SobreRoute
  ApiChatRoute: typeof ApiChatRoute
  BlogSlugRoute: typeof BlogSlugRoute
  NoticiasSlugRoute: typeof NoticiasSlugRoute
  ServicosSlugRoute: typeof ServicosSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  NoticiasIndexRoute: typeof NoticiasIndexRoute
  ServicosIndexRoute: typeof ServicosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ia': {
      id: '/ia'
      path: '/ia'
      fullPath: '/ia'
      preLoaderRoute: typeof IaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cultura': {
      id: '/cultura'
      path: '/cultura'
      fullPath: '/cultura'
      preLoaderRoute: typeof CulturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/': {
      id: '/servicos/'
      path: '/servicos'
      fullPath: '/servicos/'
      preLoaderRoute: typeof ServicosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias/': {
      id: '/noticias/'
      path: '/noticias'
      fullPath: '/noticias/'
      preLoaderRoute: typeof NoticiasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/servicos/$slug': {
      id: '/servicos/$slug'
      path: '/servicos/$slug'
      fullPath: '/servicos/$slug'
      preLoaderRoute: typeof ServicosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias/$slug': {
      id: '/noticias/$slug'
      path: '/noticias/$slug'
      fullPath: '/noticias/$slug'
      preLoaderRoute: typeof NoticiasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reset-password': {
      id: '/admin/reset-password'
      path: '/reset-password'
      fullPath: '/admin/reset-password'
      preLoaderRoute: typeof AdminResetPasswordRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/news_': {
      id: '/admin/news_'
      path: '/news'
      fullPath: '/admin/news'
      preLoaderRoute: typeof AdminNewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/instagram': {
      id: '/admin/instagram'
      path: '/instagram'
      fullPath: '/admin/instagram'
      preLoaderRoute: typeof AdminInstagramRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/import': {
      id: '/admin/import'
      path: '/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AdminImportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/forgot-password': {
      id: '/admin/forgot-password'
      path: '/forgot-password'
      fullPath: '/admin/forgot-password'
      preLoaderRoute: typeof AdminForgotPasswordRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/faq': {
      id: '/admin/faq'
      path: '/faq'
      fullPath: '/admin/faq'
      preLoaderRoute: typeof AdminFaqRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cases_': {
      id: '/admin/cases_'
      path: '/cases'
      fullPath: '/admin/cases'
      preLoaderRoute: typeof AdminCasesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog_': {
      id: '/admin/blog_'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/news/$id': {
      id: '/admin/news/$id'
      path: '/news/$id'
      fullPath: '/admin/news/$id'
      preLoaderRoute: typeof AdminNewsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cases/$id': {
      id: '/admin/cases/$id'
      path: '/cases/$id'
      fullPath: '/admin/cases/$id'
      preLoaderRoute: typeof AdminCasesIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog/$id': {
      id: '/admin/blog/$id'
      path: '/blog/$id'
      fullPath: '/admin/blog/$id'
      preLoaderRoute: typeof AdminBlogIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminBlogRoute: typeof AdminBlogRoute
  AdminCasesRoute: typeof AdminCasesRoute
  AdminFaqRoute: typeof AdminFaqRoute
  AdminForgotPasswordRoute: typeof AdminForgotPasswordRoute
  AdminImportRoute: typeof AdminImportRoute
  AdminInstagramRoute: typeof AdminInstagramRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminNewsRoute: typeof AdminNewsRoute
  AdminResetPasswordRoute: typeof AdminResetPasswordRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBlogIdRoute: typeof AdminBlogIdRoute
  AdminCasesIdRoute: typeof AdminCasesIdRoute
  AdminNewsIdRoute: typeof AdminNewsIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminBlogRoute: AdminBlogRoute,
  AdminCasesRoute: AdminCasesRoute,
  AdminFaqRoute: AdminFaqRoute,
  AdminForgotPasswordRoute: AdminForgotPasswordRoute,
  AdminImportRoute: AdminImportRoute,
  AdminInstagramRoute: AdminInstagramRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminNewsRoute: AdminNewsRoute,
  AdminResetPasswordRoute: AdminResetPasswordRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminBlogIdRoute: AdminBlogIdRoute,
  AdminCasesIdRoute: AdminCasesIdRoute,
  AdminNewsIdRoute: AdminNewsIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CasesRoute: CasesRoute,
  ContatoRoute: ContatoRoute,
  CulturaRoute: CulturaRoute,
  IaRoute: IaRoute,
  SobreRoute: SobreRoute,
  ApiChatRoute: ApiChatRoute,
  BlogSlugRoute: BlogSlugRoute,
  NoticiasSlugRoute: NoticiasSlugRoute,
  ServicosSlugRoute: ServicosSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  NoticiasIndexRoute: NoticiasIndexRoute,
  ServicosIndexRoute: ServicosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
